export const actionTypes = {
  LIKE_POST: 'LIKE_POST',
  NEW_POST: 'NEW_POST',
  NEW_COMMENT: 'NEW_COMMENT',
  FOLLOW_USER: 'FOLLOW_USER',
	CHOOSE_TAG_PROFILE: 'CHOOSE_TAG_PROFILE',
	CHANGE_FOLLOWING_USER: 'CHANGE_FOLLOWING_USER',
	
}
