export const actionTypes = {
  LIKE_POST: 'LIKE_POST',
  NEW_POST: 'NEW_POST',
  NEW_COMMENT: 'NEW_COMMENT',
  FOLLOW_USER: 'FOLLOW_USER',
	CHANGE_FOLLOWING_USER: 'CHANGE_FOLLOWING_USER',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_POST: 'UPDATE_POST'
}
