export const actionTypes = {
  FOLLOW_USER: 'FOLLOW_USER',
  UNFOLLOW_USER: 'UNFOLLOW_USER',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_POST: 'UPDATE_POST',
  SAVE_PROFILE: 'SAVE_PROFILE',
  SHOW_POPUP: 'SHOW_POPUP',
  CLOSE_POPUP: 'CLOSE_POPUP'
}
